### ISSUE TITLE
Logic gates AND 

### ISSUE THREAD

**Issue by xXHakaseXx** [eugenelepekhin/LogicCircuit#9]
When i have one input for example const and logic gate AND shows always true when only one input is true.
![obraz](https://user-images.githubusercontent.com/67443169/192764818-dca5f687-3a1f-45fc-b942-fbe3436c206f.png)

**Comment by eugenelepekhin** [comment]
The AND function is only defined on two inputs, so if you provide only one it's behavior is undefined.

**Comment by xXHakaseXx** [comment]
![LogicCircuit_oskAvvHzfm](https://user-images.githubusercontent.com/67443169/192900768-5ee49f6a-056a-41fd-8b1a-668247200501.png)
![LogicCircuit_8UXXrGlSIw](https://user-images.githubusercontent.com/67443169/192900846-bfc7a6cb-aeaa-4364-843d-44a26f2df7c7.png)
![LogicCircuit_B5spNf1z6x](https://user-images.githubusercontent.com/67443169/192901088-7e77128f-8da0-41e8-93f9-4d91cc6252dd.png)

**Comment by xXHakaseXx** [comment]
But in this case i think this is real problem. :/

**Comment by xXHakaseXx** [comment]
try it yourself

**Comment by xXHakaseXx** [comment]
in larger projects this can be irritating

**Comment by eugenelepekhin** [comment]
I am sorry I don't quite follow you.
You are building full adder. and instead of connecting your circuit to actual n8mber input you partially connect some of the inputs.
I am sure if the AND gate will behave differently then, in some other circuits partially connected it will produce other strange results.
If you want your circuit behave correctly when not all the inputs are connected you should design, it that way.
In your particular case just connect all your inputs and it will work correctly. I hardly imagine why you just partially connect your adder. What are you trying to get?
If you want to verify correctness of your adder you can use truth table and filter expression: https://logiccircuit.org/TruthTable.html

**Comment by xXHakaseXx** [comment]
In my opinion, it is difficult to read anything from this table and it is easier to connect something in the right place, the slightly strange operation of the program meant that I did not quickly find an error in my system and I consider it a minus. I understand that it's hard to program an idiot-proof program, but apart from these flaws in my opinion, the program is great.

**Comment by eugenelepekhin** [comment]
Whell, it's not about idiot proof. The AND function is not defined when only one argument is provided.
Here is an [example](https://support.microsoft.com/en-us/office/and-function-5f19b2e8-e1df-4408-897a-ce285a19e9d9) of how it defined by Microsoft Excel.
In your case all conditions in test are true. You just have one condition. But still all of them are true, so by this definition the function should be true. Or course you can come up with different definition, but it would not be any better than this one.
As I mentioned with other implementations you can build different circuit that behavior is irritating.
